#!/usr/bin/env python3
"""Build, flash, and inspect this project's CYD firmware."""

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "codex-meter-1.yaml"
BUILD = ROOT / ".esphome/build/codex-meter-1/build"


def python_path():
    override = os.environ.get("ESPHOME_PYTHON")
    candidates = [override] if override else [
        ROOT / ".venv/bin/python",
        Path.home() / "Library/Application Support/io.esphome.builder/python/bin/python3",
        sys.executable,
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            probe = subprocess.run(
                [str(candidate), "-c", "import esphome, esptool, serial"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
            if probe.returncode == 0:
                return str(candidate)
    raise SystemExit("Install requirements.txt into .venv, or set ESPHOME_PYTHON.")


def run(python, module, *args):
    subprocess.run([python, "-m", module, *map(str, args)], cwd=ROOT, check=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["validate", "build", "flash", "verify", "logs", "sync-builder"])
    parser.add_argument("--port", help="USB serial device; required for flash/verify/logs")
    parser.add_argument("--baud", type=int, default=115200, help="Flash/verify speed (default: 115200)")
    parser.add_argument("--builder-directory", type=Path, help="Existing Device Builder configuration directory")
    args = parser.parse_args()
    if args.command in {"flash", "verify", "logs"} and not args.port:
        parser.error("--port is required; select the connected display explicitly")
    if args.command == "sync-builder":
        if not args.builder_directory or not args.builder_directory.is_dir():
            parser.error("--builder-directory must name an existing configuration directory")
        target = args.builder_directory / CONFIG.name
        if target.resolve() == CONFIG.resolve():
            parser.error("The Builder directory must be separate from this repository")
        if target.exists():
            backup = ROOT / "artifacts/private" / ("builder-" + datetime.now().strftime("%Y%m%d-%H%M%S-%f") + ".yaml")
            backup.parent.mkdir(parents=True, exist_ok=True)
            with backup.open("xb") as output:
                os.chmod(backup, 0o600)
                output.write(target.read_bytes())
        # Local components resolve relative to the dashboard config.
        source = CONFIG.read_text().replace("path: firmware/components",
                                "path: " + json.dumps(str(ROOT / "firmware/components")))
        target.write_text("# Generated by scripts/firmware.py sync-builder. Edit the project source.\n" + source)
        print(f"Updated {target}")
        return
    python = python_path()
    if args.command == "validate":
        run(python, "esphome", "config", CONFIG)
    elif args.command == "build":
        run(python, "esphome", "compile", CONFIG)
    elif args.command == "logs":
        run(python, "esphome", "logs", CONFIG, "--device", args.port)
    else:
        manifest = BUILD / "flasher_args.json"
        if not manifest.is_file():
            parser.error("No firmware build found. Run the build command first.")
        flash = json.loads(manifest.read_text())
        files = []
        for offset, relative in sorted(flash["flash_files"].items(), key=lambda item: int(item[0], 0)):
            binary = BUILD / relative
            if not binary.is_file():
                parser.error(f"Missing firmware artifact: {binary}")
            files.extend([offset, binary])
        # Separate files use the offsets emitted by ESP-IDF. No guessed factory offset.
        # esptool verifies each written region and raises on a hash mismatch.
        command = "write-flash" if args.command == "flash" else "verify-flash"
        run(python, "esptool", "--chip", "esp32", "--port", args.port,
            "--baud", args.baud, command, *files)


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        sys.exit(exc.returncode)
    except KeyboardInterrupt:
        sys.exit(130)
